//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal {
    
    
    public partial class AdminNewsManager {
        
        /// <summary>
        /// UCAdminNewsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminNewsList UCAdminNewsList;
        
        /// <summary>
        /// UCAdminNewsEdit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminNewsEdit UCAdminNewsEdit1;
        
        /// <summary>
        /// UCAdminNewsCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminNewsCreate UCAdminNewsCreate;
        
        /// <summary>
        /// UCAdminUploadFile1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminUploadFile UCAdminUploadFile1;
    }
}
