//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal {
    
    
    public partial class WebForm3 {
        
        /// <summary>
        /// UCAdminTaiNguyenList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.WebUserControl1 UCAdminTaiNguyenList;
        
        /// <summary>
        /// UCAdminTaiNguyenList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.WebUserControl1 UCAdminTaiNguyenList1;
        
        /// <summary>
        /// UCAdminTaiNguyenCreate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminTaiNguyenCreate UCAdminTaiNguyenCreate;
    }
}
