//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal {
    
    
    public partial class AdminLoaiTinManager {
        
        /// <summary>
        /// UCAdminLoaiTinList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinList UCAdminLoaiTinList1;
        
        /// <summary>
        /// UCAdminLoaiTinList2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinList UCAdminLoaiTinList2;
        
        /// <summary>
        /// UCAdminLoaiTinEdit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinEdit UCAdminLoaiTinEdit1;
        
        /// <summary>
        /// UCAdminLoaiTinCreate1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinCreate UCAdminLoaiTinCreate1;
        
        /// <summary>
        /// UCAdminLoaiTinCreateChild1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinCreateChild UCAdminLoaiTinCreateChild1;
        
        /// <summary>
        /// UCAdminLoaiTinListChild1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinLv2List UCAdminLoaiTinListChild1;
        
        /// <summary>
        /// UCAdminLoaiTinEditChild1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinEditChild UCAdminLoaiTinEditChild1;
        
        /// <summary>
        /// UCAdminLoaiTinList3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinList UCAdminLoaiTinList3;
        
        /// <summary>
        /// UCAdminLoaiTinListChild2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebPortal.AdminUsercontrols.UCAdminLoaiTinLv2List UCAdminLoaiTinListChild2;
    }
}
